### ISSUE TITLE
Event object has no attribute hass

### ISSUE THREAD

**Issue by MikeBP13** [slashback100/presence_simulation#205]
After updating to 5.2, the integration logs the following error after HA restart:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/presence_simulation/__init__.py:91
Integration: Presence Simulation (documentation, issues)
First occurred: 07:36:45 (1 occurrence)
Last logged: 07:36:45

Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/config/custom_components/presence_simulation/__init__.py", line 91, in _launch_simulation_after_restart
    hass = event.hass
           ^^^^^^^^^^
AttributeError: 'Event' object has no attribute 'hass'
```

**Comment by slashback100** [comment]
I removed the release, for taking the time to investigate, thanks for the info.
